### ISSUE TITLE
back function after clicking on link

### ISSUE THREAD

**Issue by Shintaro-Miyazaki** [commoningtoys/commoningWebsite#1]
back function after clicking on link is not working as expected. After clicking on a link, you land on the new url, which is correct, but after clicking the back button you land on the main loading page and not the "post" where you "came from" (with the link you clicked).

**Comment by Yyyyaaaannnnoooo** [comment]
Because the link you go back you automatically reload the webpage, would be better to open the links with _blank tag added

**Comment by Shintaro-Miyazaki** [comment]
Great thanks!
